/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitIndexRouteImport } from './routes/kit/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsIdRouteRouteImport } from './routes/projects/$id/route'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects/$id/index'
import { Route as ProjectsIdBoardRouteImport } from './routes/projects/$id/board'
import { Route as ProjectsIdFilesRouteImport } from './routes/projects/$id/files'
import { Route as ProjectsIdNotesRouteImport } from './routes/projects/$id/notes'
import { Route as ProjectsIdTasksRouteImport } from './routes/projects/$id/tasks'
import { Route as ProjectsIdTimeRouteImport } from './routes/projects/$id/time'
import { Route as TasksIdIndexRouteImport } from './routes/tasks/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/kit/',
  path: '/kit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRouteRoute = ProjectsIdRouteRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const ProjectsIdBoardRoute = ProjectsIdBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const ProjectsIdFilesRoute = ProjectsIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const ProjectsIdNotesRoute = ProjectsIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const ProjectsIdTasksRoute = ProjectsIdTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const ProjectsIdTimeRoute = ProjectsIdTimeRouteImport.update({
  id: '/time',
  path: '/time',
  getParentRoute: () => ProjectsIdRouteRoute,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteRouteWithChildren
  '/kit/': typeof KitIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id/time': typeof ProjectsIdTimeRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kit': typeof KitIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id/time': typeof ProjectsIdTimeRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/tasks/$id': typeof TasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$id': typeof ProjectsIdRouteRouteWithChildren
  '/kit/': typeof KitIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$id/board': typeof ProjectsIdBoardRoute
  '/projects/$id/files': typeof ProjectsIdFilesRoute
  '/projects/$id/notes': typeof ProjectsIdNotesRoute
  '/projects/$id/tasks': typeof ProjectsIdTasksRoute
  '/projects/$id/time': typeof ProjectsIdTimeRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$id'
    | '/kit/'
    | '/projects/'
    | '/projects/$id/board'
    | '/projects/$id/files'
    | '/projects/$id/notes'
    | '/projects/$id/tasks'
    | '/projects/$id/time'
    | '/projects/$id/'
    | '/tasks/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kit'
    | '/projects'
    | '/projects/$id/board'
    | '/projects/$id/files'
    | '/projects/$id/notes'
    | '/projects/$id/tasks'
    | '/projects/$id/time'
    | '/projects/$id'
    | '/tasks/$id'
  id:
    | '__root__'
    | '/'
    | '/projects/$id'
    | '/kit/'
    | '/projects/'
    | '/projects/$id/board'
    | '/projects/$id/files'
    | '/projects/$id/notes'
    | '/projects/$id/tasks'
    | '/projects/$id/time'
    | '/projects/$id/'
    | '/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsIdRouteRoute: typeof ProjectsIdRouteRouteWithChildren
  KitIndexRoute: typeof KitIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/': {
      id: '/kit/'
      path: '/kit'
      fullPath: '/kit/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/projects/$id/board': {
      id: '/projects/$id/board'
      path: '/board'
      fullPath: '/projects/$id/board'
      preLoaderRoute: typeof ProjectsIdBoardRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/projects/$id/files': {
      id: '/projects/$id/files'
      path: '/files'
      fullPath: '/projects/$id/files'
      preLoaderRoute: typeof ProjectsIdFilesRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/projects/$id/notes': {
      id: '/projects/$id/notes'
      path: '/notes'
      fullPath: '/projects/$id/notes'
      preLoaderRoute: typeof ProjectsIdNotesRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/projects/$id/tasks': {
      id: '/projects/$id/tasks'
      path: '/tasks'
      fullPath: '/projects/$id/tasks'
      preLoaderRoute: typeof ProjectsIdTasksRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/projects/$id/time': {
      id: '/projects/$id/time'
      path: '/time'
      fullPath: '/projects/$id/time'
      preLoaderRoute: typeof ProjectsIdTimeRouteImport
      parentRoute: typeof ProjectsIdRouteRoute
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsIdRouteRouteChildren {
  ProjectsIdBoardRoute: typeof ProjectsIdBoardRoute
  ProjectsIdFilesRoute: typeof ProjectsIdFilesRoute
  ProjectsIdNotesRoute: typeof ProjectsIdNotesRoute
  ProjectsIdTasksRoute: typeof ProjectsIdTasksRoute
  ProjectsIdTimeRoute: typeof ProjectsIdTimeRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteRouteChildren: ProjectsIdRouteRouteChildren = {
  ProjectsIdBoardRoute: ProjectsIdBoardRoute,
  ProjectsIdFilesRoute: ProjectsIdFilesRoute,
  ProjectsIdNotesRoute: ProjectsIdNotesRoute,
  ProjectsIdTasksRoute: ProjectsIdTasksRoute,
  ProjectsIdTimeRoute: ProjectsIdTimeRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteRouteWithChildren = ProjectsIdRouteRoute._addFileChildren(
  ProjectsIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsIdRouteRoute: ProjectsIdRouteRouteWithChildren,
  KitIndexRoute: KitIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
