/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KitIndexRouteImport } from './routes/kit/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as TasksIdIndexRouteImport } from './routes/tasks/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/kit/',
  path: '/kit/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdIndexRoute = TasksIdIndexRouteImport.update({
  id: '/tasks/$id/',
  path: '/tasks/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kit/': typeof KitIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kit': typeof KitIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/tasks/$id': typeof TasksIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kit/': typeof KitIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/tasks/$id/': typeof TasksIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kit/' | '/projects/' | '/tasks/$id/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kit' | '/projects' | '/tasks/$id'
  id: '__root__' | '/' | '/kit/' | '/projects/' | '/tasks/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KitIndexRoute: typeof KitIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  TasksIdIndexRoute: typeof TasksIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit/': {
      id: '/kit/'
      path: '/kit'
      fullPath: '/kit/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id/': {
      id: '/tasks/$id/'
      path: '/tasks/$id'
      fullPath: '/tasks/$id/'
      preLoaderRoute: typeof TasksIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KitIndexRoute: KitIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  TasksIdIndexRoute: TasksIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
